FROM golang:1.19-buster AS build

RUN mkdir /app
WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

ADD . /app/
COPY *.go ./

RUN GOOS=linux GOARCH=arm go build -o /urlshorten

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /urlshorten /urlshorten
COPY config.sample.json /config.json

EXPOSE 8080

ENTRYPOINT [ "/urlshorten" ]
CMD [ "config.json" ]